// <auto-generated />
using System;
using Labology.DataAcess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labology.DataAcess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240430051914_AddClientTodb")]
    partial class AddClientTodb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labology.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LandMark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Mobile")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("OfficerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Pin")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Pos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Total")
                        .IsRequired()
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OfficerId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CName = "Fortune of Time",
                            Dist = "SWD9999001",
                            ImageUrl = "",
                            LandMark = "Near bara gachha",
                            Mobile = 123456789,
                            OfficerId = 1,
                            Pin = 90,
                            Pos = "Pankapal",
                            Total = 1399.0
                        },
                        new
                        {
                            Id = 2,
                            CName = "Fortune of Time",
                            Dist = "SWD9999001",
                            ImageUrl = "",
                            LandMark = "Near bara gachha",
                            Mobile = 123456789,
                            OfficerId = 2,
                            Pin = 90,
                            Pos = "Pankapal",
                            Total = 1399.0
                        },
                        new
                        {
                            Id = 3,
                            CName = "Fortune of Time",
                            Dist = "SWD9999001",
                            ImageUrl = "",
                            LandMark = "Near bara gachha",
                            Mobile = 123456789,
                            OfficerId = 1,
                            Pin = 90,
                            Pos = "Pankapal",
                            Total = 1399.0
                        },
                        new
                        {
                            Id = 4,
                            CName = "Fortune of Time",
                            Dist = "SWD9999001",
                            ImageUrl = "",
                            LandMark = "Near bara gachha",
                            Mobile = 123456789,
                            OfficerId = 2,
                            Pin = 90,
                            Pos = "Pankapal",
                            Total = 1399.0
                        },
                        new
                        {
                            Id = 5,
                            CName = "Fortune of Time",
                            Dist = "SWD9999001",
                            ImageUrl = "",
                            LandMark = "Near bara gachha",
                            Mobile = 123456789,
                            OfficerId = 1,
                            Pin = 90,
                            Pos = "Pankapal",
                            Total = 1399.0
                        },
                        new
                        {
                            Id = 6,
                            CName = "Fortune of Time",
                            Dist = "SWD9999001",
                            ImageUrl = "",
                            LandMark = "Near bara gachha",
                            Mobile = 123456789,
                            OfficerId = 2,
                            Pin = 90,
                            Pos = "Pankapal",
                            Total = 1399.0
                        });
                });

            modelBuilder.Entity("Labology.Models.Officer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Officers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 2,
                            Name = "FeMale"
                        });
                });

            modelBuilder.Entity("Labology.Models.Client", b =>
                {
                    b.HasOne("Labology.Models.Officer", "Officer")
                        .WithMany()
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Officer");
                });
#pragma warning restore 612, 618
        }
    }
}
